---
# Include OS-specific tasks
- name: Include APT-based tasks
  include_tasks: debian.yml
  when: package_manager == "apt"

- name: Include Pacman-based tasks
  include_tasks: archlinux.yml
  when: package_manager == "pacman"

# Common tasks for all distributions
- name: Install Python development tools
  pip:
    name:
      - pipenv
      - virtualenv
      - black
      - flake8
      - pytest
      - ipython
    state: present
    executable: pip3
