---
- name: Install Python and pip
  package:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
    state: present

- name: Install Python development tools
  pip:
    name:
      - pipenv
      - virtualenv
      - black
      - flake8
      - pytest
      - ipython
    state: present
    executable: pip3

- name: Set Python3 as default python
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
  when: ansible_os_family == "Debian"
