---
galaxy_info:
  author: Your Name
  description: Install Go 1.24
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - golang
    - go
    - development

dependencies: []
