---
- name: Setup Development Environment
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  roles:
    - common
    - zsh
    - python
    - nodejs
    - golang
    - docker
