---
- name: Update apt cache (Ubuntu/Debian)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install common development packages
  package:
    name:
      - git
      - curl
      - wget
      - vim
      - build-essential
      - linux-headers-generic
      - make
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == "Debian"

- name: Create development directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ~/workspace
    - ~/tools
    - ~/.config
