---
# Include OS-specific tasks
- name: Include Debian/Ubuntu tasks
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include Arch Linux tasks
  include_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"

# Common tasks for all distributions
- name: Create development directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ~/workspace
    - ~/tools
    - ~/.config

# Install Lazygit (common for all distributions)
- name: Check if lazygit is installed
  command: which lazygit
  register: lazygit_check
  failed_when: false
  changed_when: false

- name: Get latest lazygit version
  uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    return_content: yes
  register: lazygit_latest
  when: lazygit_check.rc != 0

- name: Download lazygit binary
  get_url:
    url: "https://github.com/jesseduffield/lazygit/releases/download/{{ lazygit_latest.json.tag_name }}/lazygit_{{ lazygit_latest.json.tag_name[1:] }}_Linux_x86_64.tar.gz"
    dest: /tmp/lazygit.tar.gz
    mode: '0644'
  when: lazygit_check.rc != 0

- name: Extract lazygit
  unarchive:
    src: /tmp/lazygit.tar.gz
    dest: /tmp
    remote_src: yes
  when: lazygit_check.rc != 0

- name: Install lazygit
  copy:
    src: /tmp/lazygit
    dest: /usr/local/bin/lazygit
    mode: '0755'
    remote_src: yes
  become: yes
  when: lazygit_check.rc != 0